language: ruby
rvm:
  - rvm 2.1.1
  - rvm 2.3.1
services:
  - postgresql

before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate

env:
  global:
    - TWILIO_ACCOUNT_SID=TWILIOACCOUNTSID0000
    - TWILIO_AUTH_TOKEN=TWILIOAUTHTOKEN00000
    - TWILIO_NUMBER=+12345555555
